# Generated by Django 5.0.7 on 2026-03-20 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectupdate_projectupdateimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_interests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectinterest',
            constraint=models.UniqueConstraint(fields=('project', 'email'), name='unique_project_interest_email'),
        ),
    ]
