# Generated by Django 5.0.7 on 2026-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('livelihood', 'Livelihood'), ('women_empowerment', 'Women Empowerment'), ('youth_empowerment', 'Youth Empowerment'), ('community_development', 'Community Development'), ('environment', 'Environment'), ('emergency_relief', 'Emergency Relief'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
